#!/bin/bash

MUJ_KEY_PATH=$(locate -b 'mjkey.txt')

if [ -z "$MUJ_KEY_PATH" ]
then
      echo "Path to Mujoco key NOT found!"
else
      echo "Path to Mujoco key found!"
      export MUJ_KEY_PATH
fi


